version: "3"

services:
  app:
      build: .
      container_name: "hrezend-challenge-coodesh2021"
      restart: always
      command: npm start
      ports:
        - "3333:3333"
      volumes:
        - .:/home/app